from typing import Final
from alpyro_msgs import RosMessage
from alpyro_msgs.turtle_actionlib.shapeactionfeedback import ShapeActionFeedback
from alpyro_msgs.turtle_actionlib.shapeactiongoal import ShapeActionGoal
from alpyro_msgs.turtle_actionlib.shapeactionresult import ShapeActionResult


class ShapeAction(RosMessage):
  __msg_typ__ = "turtle_actionlib/ShapeAction"
  __msg_def__ = "dHVydGxlX2FjdGlvbmxpYi9TaGFwZUFjdGlvbkdvYWwgYWN0aW9uX2dvYWwKICBzdGRfbXNncy9IZWFkZXIgaGVhZGVyCiAgICB1aW50MzIgc2VxCiAgICB0aW1lIHN0YW1wCiAgICBzdHJpbmcgZnJhbWVfaWQKICBhY3Rpb25saWJfbXNncy9Hb2FsSUQgZ29hbF9pZAogICAgdGltZSBzdGFtcAogICAgc3RyaW5nIGlkCiAgdHVydGxlX2FjdGlvbmxpYi9TaGFwZUdvYWwgZ29hbAogICAgaW50MzIgZWRnZXMKICAgIGZsb2F0MzIgcmFkaXVzCnR1cnRsZV9hY3Rpb25saWIvU2hhcGVBY3Rpb25SZXN1bHQgYWN0aW9uX3Jlc3VsdAogIHN0ZF9tc2dzL0hlYWRlciBoZWFkZXIKICAgIHVpbnQzMiBzZXEKICAgIHRpbWUgc3RhbXAKICAgIHN0cmluZyBmcmFtZV9pZAogIGFjdGlvbmxpYl9tc2dzL0dvYWxTdGF0dXMgc3RhdHVzCiAgICB1aW50OCBQRU5ESU5HPTAKICAgIHVpbnQ4IEFDVElWRT0xCiAgICB1aW50OCBQUkVFTVBURUQ9MgogICAgdWludDggU1VDQ0VFREVEPTMKICAgIHVpbnQ4IEFCT1JURUQ9NAogICAgdWludDggUkVKRUNURUQ9NQogICAgdWludDggUFJFRU1QVElORz02CiAgICB1aW50OCBSRUNBTExJTkc9NwogICAgdWludDggUkVDQUxMRUQ9OAogICAgdWludDggTE9TVD05CiAgICBhY3Rpb25saWJfbXNncy9Hb2FsSUQgZ29hbF9pZAogICAgICB0aW1lIHN0YW1wCiAgICAgIHN0cmluZyBpZAogICAgdWludDggc3RhdHVzCiAgICBzdHJpbmcgdGV4dAogIHR1cnRsZV9hY3Rpb25saWIvU2hhcGVSZXN1bHQgcmVzdWx0CiAgICBmbG9hdDMyIGludGVyaW9yX2FuZ2xlCiAgICBmbG9hdDMyIGFwb3RoZW0KdHVydGxlX2FjdGlvbmxpYi9TaGFwZUFjdGlvbkZlZWRiYWNrIGFjdGlvbl9mZWVkYmFjawogIHN0ZF9tc2dzL0hlYWRlciBoZWFkZXIKICAgIHVpbnQzMiBzZXEKICAgIHRpbWUgc3RhbXAKICAgIHN0cmluZyBmcmFtZV9pZAogIGFjdGlvbmxpYl9tc2dzL0dvYWxTdGF0dXMgc3RhdHVzCiAgICB1aW50OCBQRU5ESU5HPTAKICAgIHVpbnQ4IEFDVElWRT0xCiAgICB1aW50OCBQUkVFTVBURUQ9MgogICAgdWludDggU1VDQ0VFREVEPTMKICAgIHVpbnQ4IEFCT1JURUQ9NAogICAgdWludDggUkVKRUNURUQ9NQogICAgdWludDggUFJFRU1QVElORz02CiAgICB1aW50OCBSRUNBTExJTkc9NwogICAgdWludDggUkVDQUxMRUQ9OAogICAgdWludDggTE9TVD05CiAgICBhY3Rpb25saWJfbXNncy9Hb2FsSUQgZ29hbF9pZAogICAgICB0aW1lIHN0YW1wCiAgICAgIHN0cmluZyBpZAogICAgdWludDggc3RhdHVzCiAgICBzdHJpbmcgdGV4dAogIHR1cnRsZV9hY3Rpb25saWIvU2hhcGVGZWVkYmFjayBmZWVkYmFjawoK"
  __md5_sum__ = "d73b17d6237a925511f5d7727a1dc903"

  action_goal: ShapeActionGoal
  action_result: ShapeActionResult
  action_feedback: ShapeActionFeedback
