from typing import List
from typing_extensions import Annotated
from typing import Final
from alpyro_msgs import RosMessage
from alpyro_msgs.actionlib_msgs.goalstatus import GoalStatus
from alpyro_msgs.nav_msgs.getmapresult import GetMapResult
from alpyro_msgs.std_msgs.header import Header


class GetMapActionResult(RosMessage):
  __msg_typ__ = "nav_msgs/GetMapActionResult"
  __msg_def__ = "c3RkX21zZ3MvSGVhZGVyIGhlYWRlcgogIHVpbnQzMiBzZXEKICB0aW1lIHN0YW1wCiAgc3RyaW5nIGZyYW1lX2lkCmFjdGlvbmxpYl9tc2dzL0dvYWxTdGF0dXMgc3RhdHVzCiAgdWludDggUEVORElORz0wCiAgdWludDggQUNUSVZFPTEKICB1aW50OCBQUkVFTVBURUQ9MgogIHVpbnQ4IFNVQ0NFRURFRD0zCiAgdWludDggQUJPUlRFRD00CiAgdWludDggUkVKRUNURUQ9NQogIHVpbnQ4IFBSRUVNUFRJTkc9NgogIHVpbnQ4IFJFQ0FMTElORz03CiAgdWludDggUkVDQUxMRUQ9OAogIHVpbnQ4IExPU1Q9OQogIGFjdGlvbmxpYl9tc2dzL0dvYWxJRCBnb2FsX2lkCiAgICB0aW1lIHN0YW1wCiAgICBzdHJpbmcgaWQKICB1aW50OCBzdGF0dXMKICBzdHJpbmcgdGV4dApuYXZfbXNncy9HZXRNYXBSZXN1bHQgcmVzdWx0CiAgbmF2X21zZ3MvT2NjdXBhbmN5R3JpZCBtYXAKICAgIHN0ZF9tc2dzL0hlYWRlciBoZWFkZXIKICAgICAgdWludDMyIHNlcQogICAgICB0aW1lIHN0YW1wCiAgICAgIHN0cmluZyBmcmFtZV9pZAogICAgbmF2X21zZ3MvTWFwTWV0YURhdGEgaW5mbwogICAgICB0aW1lIG1hcF9sb2FkX3RpbWUKICAgICAgZmxvYXQzMiByZXNvbHV0aW9uCiAgICAgIHVpbnQzMiB3aWR0aAogICAgICB1aW50MzIgaGVpZ2h0CiAgICAgIGdlb21ldHJ5X21zZ3MvUG9zZSBvcmlnaW4KICAgICAgICBnZW9tZXRyeV9tc2dzL1BvaW50IHBvc2l0aW9uCiAgICAgICAgICBmbG9hdDY0IHgKICAgICAgICAgIGZsb2F0NjQgeQogICAgICAgICAgZmxvYXQ2NCB6CiAgICAgICAgZ2VvbWV0cnlfbXNncy9RdWF0ZXJuaW9uIG9yaWVudGF0aW9uCiAgICAgICAgICBmbG9hdDY0IHgKICAgICAgICAgIGZsb2F0NjQgeQogICAgICAgICAgZmxvYXQ2NCB6CiAgICAgICAgICBmbG9hdDY0IHcKICAgIGludDhbXSBkYXRhCgo="
  __md5_sum__ = "ac66e5b9a79bb4bbd33dab245236c892"

  header: Header
  status: GoalStatus
  result: GetMapResult
