from typing import List
from typing_extensions import Annotated
from alpyro_msgs import RosMessage
from alpyro_msgs.nav_msgs.occupancygrid import OccupancyGrid


class GetMapResult(RosMessage):
  __msg_typ__ = "nav_msgs/GetMapResult"
  __msg_def__ = "bmF2X21zZ3MvT2NjdXBhbmN5R3JpZCBtYXAKICBzdGRfbXNncy9IZWFkZXIgaGVhZGVyCiAgICB1aW50MzIgc2VxCiAgICB0aW1lIHN0YW1wCiAgICBzdHJpbmcgZnJhbWVfaWQKICBuYXZfbXNncy9NYXBNZXRhRGF0YSBpbmZvCiAgICB0aW1lIG1hcF9sb2FkX3RpbWUKICAgIGZsb2F0MzIgcmVzb2x1dGlvbgogICAgdWludDMyIHdpZHRoCiAgICB1aW50MzIgaGVpZ2h0CiAgICBnZW9tZXRyeV9tc2dzL1Bvc2Ugb3JpZ2luCiAgICAgIGdlb21ldHJ5X21zZ3MvUG9pbnQgcG9zaXRpb24KICAgICAgICBmbG9hdDY0IHgKICAgICAgICBmbG9hdDY0IHkKICAgICAgICBmbG9hdDY0IHoKICAgICAgZ2VvbWV0cnlfbXNncy9RdWF0ZXJuaW9uIG9yaWVudGF0aW9uCiAgICAgICAgZmxvYXQ2NCB4CiAgICAgICAgZmxvYXQ2NCB5CiAgICAgICAgZmxvYXQ2NCB6CiAgICAgICAgZmxvYXQ2NCB3CiAgaW50OFtdIGRhdGEKCg=="
  __md5_sum__ = "6cdd0a18e0aff5b0a3ca2326a89b54ff"

  map: OccupancyGrid
