from typing import List
from typing_extensions import Annotated
from alpyro_msgs import RosMessage, duration
from alpyro_msgs.control_msgs.jointtolerance import JointTolerance
from alpyro_msgs.trajectory_msgs.jointtrajectory import JointTrajectory


class FollowJointTrajectoryGoal(RosMessage):
  __msg_typ__ = "control_msgs/FollowJointTrajectoryGoal"
  __msg_def__ = "dHJhamVjdG9yeV9tc2dzL0pvaW50VHJhamVjdG9yeSB0cmFqZWN0b3J5CiAgc3RkX21zZ3MvSGVhZGVyIGhlYWRlcgogICAgdWludDMyIHNlcQogICAgdGltZSBzdGFtcAogICAgc3RyaW5nIGZyYW1lX2lkCiAgc3RyaW5nW10gam9pbnRfbmFtZXMKICB0cmFqZWN0b3J5X21zZ3MvSm9pbnRUcmFqZWN0b3J5UG9pbnRbXSBwb2ludHMKICAgIGZsb2F0NjRbXSBwb3NpdGlvbnMKICAgIGZsb2F0NjRbXSB2ZWxvY2l0aWVzCiAgICBmbG9hdDY0W10gYWNjZWxlcmF0aW9ucwogICAgZmxvYXQ2NFtdIGVmZm9ydAogICAgZHVyYXRpb24gdGltZV9mcm9tX3N0YXJ0CmNvbnRyb2xfbXNncy9Kb2ludFRvbGVyYW5jZVtdIHBhdGhfdG9sZXJhbmNlCiAgc3RyaW5nIG5hbWUKICBmbG9hdDY0IHBvc2l0aW9uCiAgZmxvYXQ2NCB2ZWxvY2l0eQogIGZsb2F0NjQgYWNjZWxlcmF0aW9uCmNvbnRyb2xfbXNncy9Kb2ludFRvbGVyYW5jZVtdIGdvYWxfdG9sZXJhbmNlCiAgc3RyaW5nIG5hbWUKICBmbG9hdDY0IHBvc2l0aW9uCiAgZmxvYXQ2NCB2ZWxvY2l0eQogIGZsb2F0NjQgYWNjZWxlcmF0aW9uCmR1cmF0aW9uIGdvYWxfdGltZV90b2xlcmFuY2UKCg=="
  __md5_sum__ = "69636787b6ecbde4d61d711979bc7ecb"

  trajectory: JointTrajectory
  path_tolerance: Annotated[List[JointTolerance], 0, 0]
  goal_tolerance: Annotated[List[JointTolerance], 0, 0]
  goal_time_tolerance: duration
