from typing import Final
from alpyro_msgs import RosMessage
from alpyro_msgs.actionlib_msgs.goalstatus import GoalStatus
from alpyro_msgs.control_msgs.followjointtrajectoryresult import FollowJointTrajectoryResult
from alpyro_msgs.std_msgs.header import Header


class FollowJointTrajectoryActionResult(RosMessage):
  __msg_typ__ = "control_msgs/FollowJointTrajectoryActionResult"
  __msg_def__ = "c3RkX21zZ3MvSGVhZGVyIGhlYWRlcgogIHVpbnQzMiBzZXEKICB0aW1lIHN0YW1wCiAgc3RyaW5nIGZyYW1lX2lkCmFjdGlvbmxpYl9tc2dzL0dvYWxTdGF0dXMgc3RhdHVzCiAgdWludDggUEVORElORz0wCiAgdWludDggQUNUSVZFPTEKICB1aW50OCBQUkVFTVBURUQ9MgogIHVpbnQ4IFNVQ0NFRURFRD0zCiAgdWludDggQUJPUlRFRD00CiAgdWludDggUkVKRUNURUQ9NQogIHVpbnQ4IFBSRUVNUFRJTkc9NgogIHVpbnQ4IFJFQ0FMTElORz03CiAgdWludDggUkVDQUxMRUQ9OAogIHVpbnQ4IExPU1Q9OQogIGFjdGlvbmxpYl9tc2dzL0dvYWxJRCBnb2FsX2lkCiAgICB0aW1lIHN0YW1wCiAgICBzdHJpbmcgaWQKICB1aW50OCBzdGF0dXMKICBzdHJpbmcgdGV4dApjb250cm9sX21zZ3MvRm9sbG93Sm9pbnRUcmFqZWN0b3J5UmVzdWx0IHJlc3VsdAogIGludDMyIFNVQ0NFU1NGVUw9MAogIGludDMyIElOVkFMSURfR09BTD0tMQogIGludDMyIElOVkFMSURfSk9JTlRTPS0yCiAgaW50MzIgT0xEX0hFQURFUl9USU1FU1RBTVA9LTMKICBpbnQzMiBQQVRIX1RPTEVSQU5DRV9WSU9MQVRFRD0tNAogIGludDMyIEdPQUxfVE9MRVJBTkNFX1ZJT0xBVEVEPS01CiAgaW50MzIgZXJyb3JfY29kZQogIHN0cmluZyBlcnJvcl9zdHJpbmcKCg=="
  __md5_sum__ = "c4fb3b000dc9da4fd99699380efcc5d9"

  header: Header
  status: GoalStatus
  result: FollowJointTrajectoryResult
