from typing import Final
from alpyro_msgs import RosMessage
from alpyro_msgs.actionlib_msgs.goalstatus import GoalStatus
from alpyro_msgs.control_msgs.grippercommandresult import GripperCommandResult
from alpyro_msgs.std_msgs.header import Header


class GripperCommandActionResult(RosMessage):
  __msg_typ__ = "control_msgs/GripperCommandActionResult"
  __msg_def__ = "c3RkX21zZ3MvSGVhZGVyIGhlYWRlcgogIHVpbnQzMiBzZXEKICB0aW1lIHN0YW1wCiAgc3RyaW5nIGZyYW1lX2lkCmFjdGlvbmxpYl9tc2dzL0dvYWxTdGF0dXMgc3RhdHVzCiAgdWludDggUEVORElORz0wCiAgdWludDggQUNUSVZFPTEKICB1aW50OCBQUkVFTVBURUQ9MgogIHVpbnQ4IFNVQ0NFRURFRD0zCiAgdWludDggQUJPUlRFRD00CiAgdWludDggUkVKRUNURUQ9NQogIHVpbnQ4IFBSRUVNUFRJTkc9NgogIHVpbnQ4IFJFQ0FMTElORz03CiAgdWludDggUkVDQUxMRUQ9OAogIHVpbnQ4IExPU1Q9OQogIGFjdGlvbmxpYl9tc2dzL0dvYWxJRCBnb2FsX2lkCiAgICB0aW1lIHN0YW1wCiAgICBzdHJpbmcgaWQKICB1aW50OCBzdGF0dXMKICBzdHJpbmcgdGV4dApjb250cm9sX21zZ3MvR3JpcHBlckNvbW1hbmRSZXN1bHQgcmVzdWx0CiAgZmxvYXQ2NCBwb3NpdGlvbgogIGZsb2F0NjQgZWZmb3J0CiAgYm9vbCBzdGFsbGVkCiAgYm9vbCByZWFjaGVkX2dvYWwKCg=="
  __md5_sum__ = "143702cb2df0f163c5283cedc5efc6b6"

  header: Header
  status: GoalStatus
  result: GripperCommandResult
