from typing import List
from typing_extensions import Annotated
from alpyro_msgs import RosMessage
from alpyro_msgs.actionlib_msgs.goalid import GoalID
from alpyro_msgs.control_msgs.jointtrajectorygoal import JointTrajectoryGoal
from alpyro_msgs.std_msgs.header import Header


class JointTrajectoryActionGoal(RosMessage):
  __msg_typ__ = "control_msgs/JointTrajectoryActionGoal"
  __msg_def__ = "c3RkX21zZ3MvSGVhZGVyIGhlYWRlcgogIHVpbnQzMiBzZXEKICB0aW1lIHN0YW1wCiAgc3RyaW5nIGZyYW1lX2lkCmFjdGlvbmxpYl9tc2dzL0dvYWxJRCBnb2FsX2lkCiAgdGltZSBzdGFtcAogIHN0cmluZyBpZApjb250cm9sX21zZ3MvSm9pbnRUcmFqZWN0b3J5R29hbCBnb2FsCiAgdHJhamVjdG9yeV9tc2dzL0pvaW50VHJhamVjdG9yeSB0cmFqZWN0b3J5CiAgICBzdGRfbXNncy9IZWFkZXIgaGVhZGVyCiAgICAgIHVpbnQzMiBzZXEKICAgICAgdGltZSBzdGFtcAogICAgICBzdHJpbmcgZnJhbWVfaWQKICAgIHN0cmluZ1tdIGpvaW50X25hbWVzCiAgICB0cmFqZWN0b3J5X21zZ3MvSm9pbnRUcmFqZWN0b3J5UG9pbnRbXSBwb2ludHMKICAgICAgZmxvYXQ2NFtdIHBvc2l0aW9ucwogICAgICBmbG9hdDY0W10gdmVsb2NpdGllcwogICAgICBmbG9hdDY0W10gYWNjZWxlcmF0aW9ucwogICAgICBmbG9hdDY0W10gZWZmb3J0CiAgICAgIGR1cmF0aW9uIHRpbWVfZnJvbV9zdGFydAoK"
  __md5_sum__ = "a99e83ef6185f9fdd7693efe99623a86"

  header: Header
  goal_id: GoalID
  goal: JointTrajectoryGoal
