from typing import List
from typing_extensions import Annotated
from typing import Final
from alpyro_msgs import RosMessage
from alpyro_msgs.control_msgs.jointtrajectoryactionfeedback import JointTrajectoryActionFeedback
from alpyro_msgs.control_msgs.jointtrajectoryactiongoal import JointTrajectoryActionGoal
from alpyro_msgs.control_msgs.jointtrajectoryactionresult import JointTrajectoryActionResult


class JointTrajectoryAction(RosMessage):
  __msg_typ__ = "control_msgs/JointTrajectoryAction"
  __msg_def__ = "Y29udHJvbF9tc2dzL0pvaW50VHJhamVjdG9yeUFjdGlvbkdvYWwgYWN0aW9uX2dvYWwKICBzdGRfbXNncy9IZWFkZXIgaGVhZGVyCiAgICB1aW50MzIgc2VxCiAgICB0aW1lIHN0YW1wCiAgICBzdHJpbmcgZnJhbWVfaWQKICBhY3Rpb25saWJfbXNncy9Hb2FsSUQgZ29hbF9pZAogICAgdGltZSBzdGFtcAogICAgc3RyaW5nIGlkCiAgY29udHJvbF9tc2dzL0pvaW50VHJhamVjdG9yeUdvYWwgZ29hbAogICAgdHJhamVjdG9yeV9tc2dzL0pvaW50VHJhamVjdG9yeSB0cmFqZWN0b3J5CiAgICAgIHN0ZF9tc2dzL0hlYWRlciBoZWFkZXIKICAgICAgICB1aW50MzIgc2VxCiAgICAgICAgdGltZSBzdGFtcAogICAgICAgIHN0cmluZyBmcmFtZV9pZAogICAgICBzdHJpbmdbXSBqb2ludF9uYW1lcwogICAgICB0cmFqZWN0b3J5X21zZ3MvSm9pbnRUcmFqZWN0b3J5UG9pbnRbXSBwb2ludHMKICAgICAgICBmbG9hdDY0W10gcG9zaXRpb25zCiAgICAgICAgZmxvYXQ2NFtdIHZlbG9jaXRpZXMKICAgICAgICBmbG9hdDY0W10gYWNjZWxlcmF0aW9ucwogICAgICAgIGZsb2F0NjRbXSBlZmZvcnQKICAgICAgICBkdXJhdGlvbiB0aW1lX2Zyb21fc3RhcnQKY29udHJvbF9tc2dzL0pvaW50VHJhamVjdG9yeUFjdGlvblJlc3VsdCBhY3Rpb25fcmVzdWx0CiAgc3RkX21zZ3MvSGVhZGVyIGhlYWRlcgogICAgdWludDMyIHNlcQogICAgdGltZSBzdGFtcAogICAgc3RyaW5nIGZyYW1lX2lkCiAgYWN0aW9ubGliX21zZ3MvR29hbFN0YXR1cyBzdGF0dXMKICAgIHVpbnQ4IFBFTkRJTkc9MAogICAgdWludDggQUNUSVZFPTEKICAgIHVpbnQ4IFBSRUVNUFRFRD0yCiAgICB1aW50OCBTVUNDRUVERUQ9MwogICAgdWludDggQUJPUlRFRD00CiAgICB1aW50OCBSRUpFQ1RFRD01CiAgICB1aW50OCBQUkVFTVBUSU5HPTYKICAgIHVpbnQ4IFJFQ0FMTElORz03CiAgICB1aW50OCBSRUNBTExFRD04CiAgICB1aW50OCBMT1NUPTkKICAgIGFjdGlvbmxpYl9tc2dzL0dvYWxJRCBnb2FsX2lkCiAgICAgIHRpbWUgc3RhbXAKICAgICAgc3RyaW5nIGlkCiAgICB1aW50OCBzdGF0dXMKICAgIHN0cmluZyB0ZXh0CiAgY29udHJvbF9tc2dzL0pvaW50VHJhamVjdG9yeVJlc3VsdCByZXN1bHQKY29udHJvbF9tc2dzL0pvaW50VHJhamVjdG9yeUFjdGlvbkZlZWRiYWNrIGFjdGlvbl9mZWVkYmFjawogIHN0ZF9tc2dzL0hlYWRlciBoZWFkZXIKICAgIHVpbnQzMiBzZXEKICAgIHRpbWUgc3RhbXAKICAgIHN0cmluZyBmcmFtZV9pZAogIGFjdGlvbmxpYl9tc2dzL0dvYWxTdGF0dXMgc3RhdHVzCiAgICB1aW50OCBQRU5ESU5HPTAKICAgIHVpbnQ4IEFDVElWRT0xCiAgICB1aW50OCBQUkVFTVBURUQ9MgogICAgdWludDggU1VDQ0VFREVEPTMKICAgIHVpbnQ4IEFCT1JURUQ9NAogICAgdWludDggUkVKRUNURUQ9NQogICAgdWludDggUFJFRU1QVElORz02CiAgICB1aW50OCBSRUNBTExJTkc9NwogICAgdWludDggUkVDQUxMRUQ9OAogICAgdWludDggTE9TVD05CiAgICBhY3Rpb25saWJfbXNncy9Hb2FsSUQgZ29hbF9pZAogICAgICB0aW1lIHN0YW1wCiAgICAgIHN0cmluZyBpZAogICAgdWludDggc3RhdHVzCiAgICBzdHJpbmcgdGV4dAogIGNvbnRyb2xfbXNncy9Kb2ludFRyYWplY3RvcnlGZWVkYmFjayBmZWVkYmFjawoK"
  __md5_sum__ = "a04ba3ee8f6a2d0985a6aeaf23d9d7ad"

  action_goal: JointTrajectoryActionGoal
  action_result: JointTrajectoryActionResult
  action_feedback: JointTrajectoryActionFeedback
