from alpyro_msgs import RosMessage
from alpyro_msgs.actionlib_msgs.goalid import GoalID
from alpyro_msgs.control_msgs.pointheadgoal import PointHeadGoal
from alpyro_msgs.std_msgs.header import Header


class PointHeadActionGoal(RosMessage):
  __msg_typ__ = "control_msgs/PointHeadActionGoal"
  __msg_def__ = "c3RkX21zZ3MvSGVhZGVyIGhlYWRlcgogIHVpbnQzMiBzZXEKICB0aW1lIHN0YW1wCiAgc3RyaW5nIGZyYW1lX2lkCmFjdGlvbmxpYl9tc2dzL0dvYWxJRCBnb2FsX2lkCiAgdGltZSBzdGFtcAogIHN0cmluZyBpZApjb250cm9sX21zZ3MvUG9pbnRIZWFkR29hbCBnb2FsCiAgZ2VvbWV0cnlfbXNncy9Qb2ludFN0YW1wZWQgdGFyZ2V0CiAgICBzdGRfbXNncy9IZWFkZXIgaGVhZGVyCiAgICAgIHVpbnQzMiBzZXEKICAgICAgdGltZSBzdGFtcAogICAgICBzdHJpbmcgZnJhbWVfaWQKICAgIGdlb21ldHJ5X21zZ3MvUG9pbnQgcG9pbnQKICAgICAgZmxvYXQ2NCB4CiAgICAgIGZsb2F0NjQgeQogICAgICBmbG9hdDY0IHoKICBnZW9tZXRyeV9tc2dzL1ZlY3RvcjMgcG9pbnRpbmdfYXhpcwogICAgZmxvYXQ2NCB4CiAgICBmbG9hdDY0IHkKICAgIGZsb2F0NjQgegogIHN0cmluZyBwb2ludGluZ19mcmFtZQogIGR1cmF0aW9uIG1pbl9kdXJhdGlvbgogIGZsb2F0NjQgbWF4X3ZlbG9jaXR5Cgo="
  __md5_sum__ = "b53a8323d0ba7b310ba17a2d3a82a6b8"

  header: Header
  goal_id: GoalID
  goal: PointHeadGoal
