from typing import Final
from alpyro_msgs import RosMessage
from alpyro_msgs.control_msgs.singlejointpositionactionfeedback import SingleJointPositionActionFeedback
from alpyro_msgs.control_msgs.singlejointpositionactiongoal import SingleJointPositionActionGoal
from alpyro_msgs.control_msgs.singlejointpositionactionresult import SingleJointPositionActionResult


class SingleJointPositionAction(RosMessage):
  __msg_typ__ = "control_msgs/SingleJointPositionAction"
  __msg_def__ = "Y29udHJvbF9tc2dzL1NpbmdsZUpvaW50UG9zaXRpb25BY3Rpb25Hb2FsIGFjdGlvbl9nb2FsCiAgc3RkX21zZ3MvSGVhZGVyIGhlYWRlcgogICAgdWludDMyIHNlcQogICAgdGltZSBzdGFtcAogICAgc3RyaW5nIGZyYW1lX2lkCiAgYWN0aW9ubGliX21zZ3MvR29hbElEIGdvYWxfaWQKICAgIHRpbWUgc3RhbXAKICAgIHN0cmluZyBpZAogIGNvbnRyb2xfbXNncy9TaW5nbGVKb2ludFBvc2l0aW9uR29hbCBnb2FsCiAgICBmbG9hdDY0IHBvc2l0aW9uCiAgICBkdXJhdGlvbiBtaW5fZHVyYXRpb24KICAgIGZsb2F0NjQgbWF4X3ZlbG9jaXR5CmNvbnRyb2xfbXNncy9TaW5nbGVKb2ludFBvc2l0aW9uQWN0aW9uUmVzdWx0IGFjdGlvbl9yZXN1bHQKICBzdGRfbXNncy9IZWFkZXIgaGVhZGVyCiAgICB1aW50MzIgc2VxCiAgICB0aW1lIHN0YW1wCiAgICBzdHJpbmcgZnJhbWVfaWQKICBhY3Rpb25saWJfbXNncy9Hb2FsU3RhdHVzIHN0YXR1cwogICAgdWludDggUEVORElORz0wCiAgICB1aW50OCBBQ1RJVkU9MQogICAgdWludDggUFJFRU1QVEVEPTIKICAgIHVpbnQ4IFNVQ0NFRURFRD0zCiAgICB1aW50OCBBQk9SVEVEPTQKICAgIHVpbnQ4IFJFSkVDVEVEPTUKICAgIHVpbnQ4IFBSRUVNUFRJTkc9NgogICAgdWludDggUkVDQUxMSU5HPTcKICAgIHVpbnQ4IFJFQ0FMTEVEPTgKICAgIHVpbnQ4IExPU1Q9OQogICAgYWN0aW9ubGliX21zZ3MvR29hbElEIGdvYWxfaWQKICAgICAgdGltZSBzdGFtcAogICAgICBzdHJpbmcgaWQKICAgIHVpbnQ4IHN0YXR1cwogICAgc3RyaW5nIHRleHQKICBjb250cm9sX21zZ3MvU2luZ2xlSm9pbnRQb3NpdGlvblJlc3VsdCByZXN1bHQKY29udHJvbF9tc2dzL1NpbmdsZUpvaW50UG9zaXRpb25BY3Rpb25GZWVkYmFjayBhY3Rpb25fZmVlZGJhY2sKICBzdGRfbXNncy9IZWFkZXIgaGVhZGVyCiAgICB1aW50MzIgc2VxCiAgICB0aW1lIHN0YW1wCiAgICBzdHJpbmcgZnJhbWVfaWQKICBhY3Rpb25saWJfbXNncy9Hb2FsU3RhdHVzIHN0YXR1cwogICAgdWludDggUEVORElORz0wCiAgICB1aW50OCBBQ1RJVkU9MQogICAgdWludDggUFJFRU1QVEVEPTIKICAgIHVpbnQ4IFNVQ0NFRURFRD0zCiAgICB1aW50OCBBQk9SVEVEPTQKICAgIHVpbnQ4IFJFSkVDVEVEPTUKICAgIHVpbnQ4IFBSRUVNUFRJTkc9NgogICAgdWludDggUkVDQUxMSU5HPTcKICAgIHVpbnQ4IFJFQ0FMTEVEPTgKICAgIHVpbnQ4IExPU1Q9OQogICAgYWN0aW9ubGliX21zZ3MvR29hbElEIGdvYWxfaWQKICAgICAgdGltZSBzdGFtcAogICAgICBzdHJpbmcgaWQKICAgIHVpbnQ4IHN0YXR1cwogICAgc3RyaW5nIHRleHQKICBjb250cm9sX21zZ3MvU2luZ2xlSm9pbnRQb3NpdGlvbkZlZWRiYWNrIGZlZWRiYWNrCiAgICBzdGRfbXNncy9IZWFkZXIgaGVhZGVyCiAgICAgIHVpbnQzMiBzZXEKICAgICAgdGltZSBzdGFtcAogICAgICBzdHJpbmcgZnJhbWVfaWQKICAgIGZsb2F0NjQgcG9zaXRpb24KICAgIGZsb2F0NjQgdmVsb2NpdHkKICAgIGZsb2F0NjQgZXJyb3IKCg=="
  __md5_sum__ = "c4a786b7d53e5d0983decf967a5a779e"

  action_goal: SingleJointPositionActionGoal
  action_result: SingleJointPositionActionResult
  action_feedback: SingleJointPositionActionFeedback
