from typing import List
from typing_extensions import Annotated
from typing import Final
from alpyro_msgs import RosMessage, boolean, float32, string, uint8
from alpyro_msgs.std_msgs.header import Header


class BatteryState(RosMessage):
  __msg_typ__ = "sensor_msgs/BatteryState"
  __msg_def__ = "dWludDggUE9XRVJfU1VQUExZX1NUQVRVU19VTktOT1dOPTAKdWludDggUE9XRVJfU1VQUExZX1NUQVRVU19DSEFSR0lORz0xCnVpbnQ4IFBPV0VSX1NVUFBMWV9TVEFUVVNfRElTQ0hBUkdJTkc9Mgp1aW50OCBQT1dFUl9TVVBQTFlfU1RBVFVTX05PVF9DSEFSR0lORz0zCnVpbnQ4IFBPV0VSX1NVUFBMWV9TVEFUVVNfRlVMTD00CnVpbnQ4IFBPV0VSX1NVUFBMWV9IRUFMVEhfVU5LTk9XTj0wCnVpbnQ4IFBPV0VSX1NVUFBMWV9IRUFMVEhfR09PRD0xCnVpbnQ4IFBPV0VSX1NVUFBMWV9IRUFMVEhfT1ZFUkhFQVQ9Mgp1aW50OCBQT1dFUl9TVVBQTFlfSEVBTFRIX0RFQUQ9Mwp1aW50OCBQT1dFUl9TVVBQTFlfSEVBTFRIX09WRVJWT0xUQUdFPTQKdWludDggUE9XRVJfU1VQUExZX0hFQUxUSF9VTlNQRUNfRkFJTFVSRT01CnVpbnQ4IFBPV0VSX1NVUFBMWV9IRUFMVEhfQ09MRD02CnVpbnQ4IFBPV0VSX1NVUFBMWV9IRUFMVEhfV0FUQ0hET0dfVElNRVJfRVhQSVJFPTcKdWludDggUE9XRVJfU1VQUExZX0hFQUxUSF9TQUZFVFlfVElNRVJfRVhQSVJFPTgKdWludDggUE9XRVJfU1VQUExZX1RFQ0hOT0xPR1lfVU5LTk9XTj0wCnVpbnQ4IFBPV0VSX1NVUFBMWV9URUNITk9MT0dZX05JTUg9MQp1aW50OCBQT1dFUl9TVVBQTFlfVEVDSE5PTE9HWV9MSU9OPTIKdWludDggUE9XRVJfU1VQUExZX1RFQ0hOT0xPR1lfTElQTz0zCnVpbnQ4IFBPV0VSX1NVUFBMWV9URUNITk9MT0dZX0xJRkU9NAp1aW50OCBQT1dFUl9TVVBQTFlfVEVDSE5PTE9HWV9OSUNEPTUKdWludDggUE9XRVJfU1VQUExZX1RFQ0hOT0xPR1lfTElNTj02CnN0ZF9tc2dzL0hlYWRlciBoZWFkZXIKICB1aW50MzIgc2VxCiAgdGltZSBzdGFtcAogIHN0cmluZyBmcmFtZV9pZApmbG9hdDMyIHZvbHRhZ2UKZmxvYXQzMiB0ZW1wZXJhdHVyZQpmbG9hdDMyIGN1cnJlbnQKZmxvYXQzMiBjaGFyZ2UKZmxvYXQzMiBjYXBhY2l0eQpmbG9hdDMyIGRlc2lnbl9jYXBhY2l0eQpmbG9hdDMyIHBlcmNlbnRhZ2UKdWludDggcG93ZXJfc3VwcGx5X3N0YXR1cwp1aW50OCBwb3dlcl9zdXBwbHlfaGVhbHRoCnVpbnQ4IHBvd2VyX3N1cHBseV90ZWNobm9sb2d5CmJvb2wgcHJlc2VudApmbG9hdDMyW10gY2VsbF92b2x0YWdlCmZsb2F0MzJbXSBjZWxsX3RlbXBlcmF0dXJlCnN0cmluZyBsb2NhdGlvbgpzdHJpbmcgc2VyaWFsX251bWJlcgoK"
  __md5_sum__ = "4ddae7f048e32fda22cac764685e3974"

  POWER_SUPPLY_STATUS_UNKNOWN: Final[uint8] = 0
  POWER_SUPPLY_STATUS_CHARGING: Final[uint8] = 1
  POWER_SUPPLY_STATUS_DISCHARGING: Final[uint8] = 2
  POWER_SUPPLY_STATUS_NOT_CHARGING: Final[uint8] = 3
  POWER_SUPPLY_STATUS_FULL: Final[uint8] = 4
  POWER_SUPPLY_HEALTH_UNKNOWN: Final[uint8] = 0
  POWER_SUPPLY_HEALTH_GOOD: Final[uint8] = 1
  POWER_SUPPLY_HEALTH_OVERHEAT: Final[uint8] = 2
  POWER_SUPPLY_HEALTH_DEAD: Final[uint8] = 3
  POWER_SUPPLY_HEALTH_OVERVOLTAGE: Final[uint8] = 4
  POWER_SUPPLY_HEALTH_UNSPEC_FAILURE: Final[uint8] = 5
  POWER_SUPPLY_HEALTH_COLD: Final[uint8] = 6
  POWER_SUPPLY_HEALTH_WATCHDOG_TIMER_EXPIRE: Final[uint8] = 7
  POWER_SUPPLY_HEALTH_SAFETY_TIMER_EXPIRE: Final[uint8] = 8
  POWER_SUPPLY_TECHNOLOGY_UNKNOWN: Final[uint8] = 0
  POWER_SUPPLY_TECHNOLOGY_NIMH: Final[uint8] = 1
  POWER_SUPPLY_TECHNOLOGY_LION: Final[uint8] = 2
  POWER_SUPPLY_TECHNOLOGY_LIPO: Final[uint8] = 3
  POWER_SUPPLY_TECHNOLOGY_LIFE: Final[uint8] = 4
  POWER_SUPPLY_TECHNOLOGY_NICD: Final[uint8] = 5
  POWER_SUPPLY_TECHNOLOGY_LIMN: Final[uint8] = 6
  header: Header
  voltage: float32
  temperature: float32
  current: float32
  charge: float32
  capacity: float32
  design_capacity: float32
  percentage: float32
  power_supply_status: uint8
  power_supply_health: uint8
  power_supply_technology: uint8
  present: boolean
  cell_voltage: Annotated[List[float32], 0, 0]
  cell_temperature: Annotated[List[float32], 0, 0]
  location: string
  serial_number: string
