from typing import List
from typing_extensions import Annotated
from typing import Final
from alpyro_msgs import RosMessage
from alpyro_msgs.actionlib_tutorials.fibonacciactionfeedback import FibonacciActionFeedback
from alpyro_msgs.actionlib_tutorials.fibonacciactiongoal import FibonacciActionGoal
from alpyro_msgs.actionlib_tutorials.fibonacciactionresult import FibonacciActionResult


class FibonacciAction(RosMessage):
  __msg_typ__ = "actionlib_tutorials/FibonacciAction"
  __msg_def__ = "YWN0aW9ubGliX3R1dG9yaWFscy9GaWJvbmFjY2lBY3Rpb25Hb2FsIGFjdGlvbl9nb2FsCiAgc3RkX21zZ3MvSGVhZGVyIGhlYWRlcgogICAgdWludDMyIHNlcQogICAgdGltZSBzdGFtcAogICAgc3RyaW5nIGZyYW1lX2lkCiAgYWN0aW9ubGliX21zZ3MvR29hbElEIGdvYWxfaWQKICAgIHRpbWUgc3RhbXAKICAgIHN0cmluZyBpZAogIGFjdGlvbmxpYl90dXRvcmlhbHMvRmlib25hY2NpR29hbCBnb2FsCiAgICBpbnQzMiBvcmRlcgphY3Rpb25saWJfdHV0b3JpYWxzL0ZpYm9uYWNjaUFjdGlvblJlc3VsdCBhY3Rpb25fcmVzdWx0CiAgc3RkX21zZ3MvSGVhZGVyIGhlYWRlcgogICAgdWludDMyIHNlcQogICAgdGltZSBzdGFtcAogICAgc3RyaW5nIGZyYW1lX2lkCiAgYWN0aW9ubGliX21zZ3MvR29hbFN0YXR1cyBzdGF0dXMKICAgIHVpbnQ4IFBFTkRJTkc9MAogICAgdWludDggQUNUSVZFPTEKICAgIHVpbnQ4IFBSRUVNUFRFRD0yCiAgICB1aW50OCBTVUNDRUVERUQ9MwogICAgdWludDggQUJPUlRFRD00CiAgICB1aW50OCBSRUpFQ1RFRD01CiAgICB1aW50OCBQUkVFTVBUSU5HPTYKICAgIHVpbnQ4IFJFQ0FMTElORz03CiAgICB1aW50OCBSRUNBTExFRD04CiAgICB1aW50OCBMT1NUPTkKICAgIGFjdGlvbmxpYl9tc2dzL0dvYWxJRCBnb2FsX2lkCiAgICAgIHRpbWUgc3RhbXAKICAgICAgc3RyaW5nIGlkCiAgICB1aW50OCBzdGF0dXMKICAgIHN0cmluZyB0ZXh0CiAgYWN0aW9ubGliX3R1dG9yaWFscy9GaWJvbmFjY2lSZXN1bHQgcmVzdWx0CiAgICBpbnQzMltdIHNlcXVlbmNlCmFjdGlvbmxpYl90dXRvcmlhbHMvRmlib25hY2NpQWN0aW9uRmVlZGJhY2sgYWN0aW9uX2ZlZWRiYWNrCiAgc3RkX21zZ3MvSGVhZGVyIGhlYWRlcgogICAgdWludDMyIHNlcQogICAgdGltZSBzdGFtcAogICAgc3RyaW5nIGZyYW1lX2lkCiAgYWN0aW9ubGliX21zZ3MvR29hbFN0YXR1cyBzdGF0dXMKICAgIHVpbnQ4IFBFTkRJTkc9MAogICAgdWludDggQUNUSVZFPTEKICAgIHVpbnQ4IFBSRUVNUFRFRD0yCiAgICB1aW50OCBTVUNDRUVERUQ9MwogICAgdWludDggQUJPUlRFRD00CiAgICB1aW50OCBSRUpFQ1RFRD01CiAgICB1aW50OCBQUkVFTVBUSU5HPTYKICAgIHVpbnQ4IFJFQ0FMTElORz03CiAgICB1aW50OCBSRUNBTExFRD04CiAgICB1aW50OCBMT1NUPTkKICAgIGFjdGlvbmxpYl9tc2dzL0dvYWxJRCBnb2FsX2lkCiAgICAgIHRpbWUgc3RhbXAKICAgICAgc3RyaW5nIGlkCiAgICB1aW50OCBzdGF0dXMKICAgIHN0cmluZyB0ZXh0CiAgYWN0aW9ubGliX3R1dG9yaWFscy9GaWJvbmFjY2lGZWVkYmFjayBmZWVkYmFjawogICAgaW50MzJbXSBzZXF1ZW5jZQoK"
  __md5_sum__ = "f59df5767bf7634684781c92598b2406"

  action_goal: FibonacciActionGoal
  action_result: FibonacciActionResult
  action_feedback: FibonacciActionFeedback
