from typing import Final
from alpyro_msgs import RosMessage, float32, string


class Constants(RosMessage):
  __msg_typ__ = "bond/Constants"
  __msg_def__ = "ZmxvYXQzMiBERUFEX1BVQkxJU0hfUEVSSU9EPTAuMDUKZmxvYXQzMiBERUZBVUxUX0NPTk5FQ1RfVElNRU9VVD0xMC4wCmZsb2F0MzIgREVGQVVMVF9IRUFSVEJFQVRfVElNRU9VVD00LjAKZmxvYXQzMiBERUZBVUxUX0RJU0NPTk5FQ1RfVElNRU9VVD0yLjAKZmxvYXQzMiBERUZBVUxUX0hFQVJUQkVBVF9QRVJJT0Q9MS4wCnN0cmluZyBESVNBQkxFX0hFQVJUQkVBVF9USU1FT1VUX1BBUkFNPS9ib25kX2Rpc2FibGVfaGVhcnRiZWF0X3RpbWVvdXQKCg=="
  __md5_sum__ = "6fc594dc1d7bd7919077042712f8c8b0"

  DEAD_PUBLISH_PERIOD: Final[float32] = 0.05
  DEFAULT_CONNECT_TIMEOUT: Final[float32] = 10.0
  DEFAULT_HEARTBEAT_TIMEOUT: Final[float32] = 4.0
  DEFAULT_DISCONNECT_TIMEOUT: Final[float32] = 2.0
  DEFAULT_HEARTBEAT_PERIOD: Final[float32] = 1.0
  DISABLE_HEARTBEAT_TIMEOUT_PARAM: Final[string] = "/bond_disable_heartbeat_timeout"
