from alpyro_msgs import RosMessage, string
from alpyro_msgs.geometry_msgs.pose import Pose
from alpyro_msgs.std_msgs.header import Header


class InteractiveMarkerPose(RosMessage):
  __msg_typ__ = "visualization_msgs/InteractiveMarkerPose"
  __msg_def__ = "c3RkX21zZ3MvSGVhZGVyIGhlYWRlcgogIHVpbnQzMiBzZXEKICB0aW1lIHN0YW1wCiAgc3RyaW5nIGZyYW1lX2lkCmdlb21ldHJ5X21zZ3MvUG9zZSBwb3NlCiAgZ2VvbWV0cnlfbXNncy9Qb2ludCBwb3NpdGlvbgogICAgZmxvYXQ2NCB4CiAgICBmbG9hdDY0IHkKICAgIGZsb2F0NjQgegogIGdlb21ldHJ5X21zZ3MvUXVhdGVybmlvbiBvcmllbnRhdGlvbgogICAgZmxvYXQ2NCB4CiAgICBmbG9hdDY0IHkKICAgIGZsb2F0NjQgegogICAgZmxvYXQ2NCB3CnN0cmluZyBuYW1lCgo="
  __md5_sum__ = "a6e6833209a196a38d798dadb02c81f8"

  header: Header
  pose: Pose
  name: string
