from typing import List
from typing_extensions import Annotated
from alpyro_msgs import RosMessage
from alpyro_msgs.dynamic_reconfigure.config import Config
from alpyro_msgs.dynamic_reconfigure.group import Group


class ConfigDescription(RosMessage):
  __msg_typ__ = "dynamic_reconfigure/ConfigDescription"
  __msg_def__ = "ZHluYW1pY19yZWNvbmZpZ3VyZS9Hcm91cFtdIGdyb3VwcwogIHN0cmluZyBuYW1lCiAgc3RyaW5nIHR5cGUKICBkeW5hbWljX3JlY29uZmlndXJlL1BhcmFtRGVzY3JpcHRpb25bXSBwYXJhbWV0ZXJzCiAgICBzdHJpbmcgbmFtZQogICAgc3RyaW5nIHR5cGUKICAgIHVpbnQzMiBsZXZlbAogICAgc3RyaW5nIGRlc2NyaXB0aW9uCiAgICBzdHJpbmcgZWRpdF9tZXRob2QKICBpbnQzMiBwYXJlbnQKICBpbnQzMiBpZApkeW5hbWljX3JlY29uZmlndXJlL0NvbmZpZyBtYXgKICBkeW5hbWljX3JlY29uZmlndXJlL0Jvb2xQYXJhbWV0ZXJbXSBib29scwogICAgc3RyaW5nIG5hbWUKICAgIGJvb2wgdmFsdWUKICBkeW5hbWljX3JlY29uZmlndXJlL0ludFBhcmFtZXRlcltdIGludHMKICAgIHN0cmluZyBuYW1lCiAgICBpbnQzMiB2YWx1ZQogIGR5bmFtaWNfcmVjb25maWd1cmUvU3RyUGFyYW1ldGVyW10gc3RycwogICAgc3RyaW5nIG5hbWUKICAgIHN0cmluZyB2YWx1ZQogIGR5bmFtaWNfcmVjb25maWd1cmUvRG91YmxlUGFyYW1ldGVyW10gZG91YmxlcwogICAgc3RyaW5nIG5hbWUKICAgIGZsb2F0NjQgdmFsdWUKICBkeW5hbWljX3JlY29uZmlndXJlL0dyb3VwU3RhdGVbXSBncm91cHMKICAgIHN0cmluZyBuYW1lCiAgICBib29sIHN0YXRlCiAgICBpbnQzMiBpZAogICAgaW50MzIgcGFyZW50CmR5bmFtaWNfcmVjb25maWd1cmUvQ29uZmlnIG1pbgogIGR5bmFtaWNfcmVjb25maWd1cmUvQm9vbFBhcmFtZXRlcltdIGJvb2xzCiAgICBzdHJpbmcgbmFtZQogICAgYm9vbCB2YWx1ZQogIGR5bmFtaWNfcmVjb25maWd1cmUvSW50UGFyYW1ldGVyW10gaW50cwogICAgc3RyaW5nIG5hbWUKICAgIGludDMyIHZhbHVlCiAgZHluYW1pY19yZWNvbmZpZ3VyZS9TdHJQYXJhbWV0ZXJbXSBzdHJzCiAgICBzdHJpbmcgbmFtZQogICAgc3RyaW5nIHZhbHVlCiAgZHluYW1pY19yZWNvbmZpZ3VyZS9Eb3VibGVQYXJhbWV0ZXJbXSBkb3VibGVzCiAgICBzdHJpbmcgbmFtZQogICAgZmxvYXQ2NCB2YWx1ZQogIGR5bmFtaWNfcmVjb25maWd1cmUvR3JvdXBTdGF0ZVtdIGdyb3VwcwogICAgc3RyaW5nIG5hbWUKICAgIGJvb2wgc3RhdGUKICAgIGludDMyIGlkCiAgICBpbnQzMiBwYXJlbnQKZHluYW1pY19yZWNvbmZpZ3VyZS9Db25maWcgZGZsdAogIGR5bmFtaWNfcmVjb25maWd1cmUvQm9vbFBhcmFtZXRlcltdIGJvb2xzCiAgICBzdHJpbmcgbmFtZQogICAgYm9vbCB2YWx1ZQogIGR5bmFtaWNfcmVjb25maWd1cmUvSW50UGFyYW1ldGVyW10gaW50cwogICAgc3RyaW5nIG5hbWUKICAgIGludDMyIHZhbHVlCiAgZHluYW1pY19yZWNvbmZpZ3VyZS9TdHJQYXJhbWV0ZXJbXSBzdHJzCiAgICBzdHJpbmcgbmFtZQogICAgc3RyaW5nIHZhbHVlCiAgZHluYW1pY19yZWNvbmZpZ3VyZS9Eb3VibGVQYXJhbWV0ZXJbXSBkb3VibGVzCiAgICBzdHJpbmcgbmFtZQogICAgZmxvYXQ2NCB2YWx1ZQogIGR5bmFtaWNfcmVjb25maWd1cmUvR3JvdXBTdGF0ZVtdIGdyb3VwcwogICAgc3RyaW5nIG5hbWUKICAgIGJvb2wgc3RhdGUKICAgIGludDMyIGlkCiAgICBpbnQzMiBwYXJlbnQKCg=="
  __md5_sum__ = "757ce9d44ba8ddd801bb30bc456f946f"

  groups: Annotated[List[Group], 0, 0]
  max: Config
  min: Config
  dflt: Config
